### ISSUE TITLE
Issues adding HC-SR04 

### ISSUE THREAD

**Issue by bjornarfonn** [theyosh/TerrariumPI#179]
First and foremost, thank you for this incredible software. Having looked for months and tried almost everything else, TerrariumPI does everything i need and so much more.

However.. there seems to be an issue adding the distance sensor.
The sensor is running fine and giving steady readings when running on sample python script.
When i try to add this in TerrariumPI (using both GPIO values comma seperated) the software stalls to a stop. Its loading for a long time when trying to submit changes.. using about 88-100% cpu on my monitor.. then it stops completely.. when this happens, the terminal window doesnt give any errors.. 
TerrariumPI eventually shows "Disconnected" and then nothing.. after a restart, im able to get it back, but the sensor was never stored.

Tried to unplug the sensors and add using the same values, and was able to add the HC-SR04 without any problems. When plugging the sensors back in and starting up again, TerrariumPI doesnt start. The terminal displays these error messages;

0.58:8090 ...                                                                                                   
2018-08-12 11:05:37,201 - ERROR   - terrariumWeather     - Error getting online data from yr.no
Traceback (most recent call last):                                                                              
  File "/home/pi/TerrariumPI/terrariumWeather.py", line 90, in load_data
    xmldata = untangle.parse(xmldata)                                                                           
  File "/usr/local/lib/python2.7/dist-packages/untangle.py", line 182, in parse
    parser.parse(StringIO(filename))                                                                            
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)                                                             
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)                                                                                           
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)                                                                           
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 136: ordinal not in range(128)

**Raspberry Pi Zero W** running **Raspbian Stretch Lite**

**EDIT**
Could this be related to GPIO.setmode ?
I noticed that when trying different scripts, the script never returns a value when running in GPIO.setmode (GPIO.BOARD), but works flawlessly when changing to GPIO.setmode (GPIO.BCM)

Could this be the case here. And can it be changed without breaking other things?

**Comment by bjornarfonn** [comment]
Could this be related to GPIO.setmode ? 
I noticed that when trying different scripts, the script never returns a value when running in GPIO.setmode (GPIO.BOARD), but works flawlessly when changing to GPIO.setmode (GPIO.BCM)

Could this be the case here. And can it be changed without breaking other things?

**Comment by theyosh** [comment]
Hmm could it be that you are using a Red Sparksfun board: https://github.com/theyosh/TerrariumPI/issues/146

Somehow they do not work. Else I should not know why this is happening.

But the error above shows problems with weather data. What is the wheater url you are using?

**Comment by bjornarfonn** [comment]
I think the weather is unrelated, but yes.. im unable to set the weather.

The URL used is: https://www.yr.no/sted/Norge/Rogaland/Klepp/
But after adding this in settings, the weather doesnt show/work.

The sparkfun board is red? or? Mine is blue and has no special numbering that describes where its from. Its not bought at sparkfun, so i doubt it.

As issue #146 mentiones, im running a 4,7k and 10k resistor voltage divider. This was suggested as a more reliable readout. As i mentioned above, when i run different python scripts to readout distance (including modmypi script) it works fine.

**Comment by Natrixz** [comment]
SparksFun is always red, however i did notice not all versions of the board work...or work dodgy.
The cheapest one works best for me>,<

**Comment by theyosh** [comment]
@bjornarfonn your weather url IS the problem. I just tried https://www.yr.no/.place/Norge/Rogaland/Klepp/ and that is going to a region where you have to select a city.  Like: https://www.yr.no/place/Norway/Rogaland/Klepp/Kleppe/ But that url is not valid as it has an extra subfolder in the url.

I have to make a fix for that. Because your current url is not specifying a city. And I have not seen weather urls that specify an extra region next to the province.

What is your right city url? I just tried Kleppe as city for example

**Comment by bjornarfonn** [comment]
https://www.yr.no/place/Norway/Rogaland/Klepp/Kleppe/
That is the correct link. Most places in Norway will have this extra subfolder
Country/Region/Municipality/City  Blame the vikings for dividing the country to tons of small municipalities.. :)

As for the HC-SR04 i will try to purchase a few other places and try some other ones.
From web searches, it doesnt really state which are the "best" or "worst" so its a guessing game..

Thanks for all support, and thanks for providing this amazing software that will soon control my koi pond, aquarium and my cabins water well 👍

**Comment by theyosh** [comment]
@bjornarfonn WAIT! I just updated the code. That should fix your weather issue. Because it was not the long url, but there was some Norwegian text (strange UTF8 chars) that broke the code.

That is now fixed, and I think it should work. I am afraid that the weather part was also blocking my software to start running. So could you give a try:

If you installed through git (steps in the README) then you can do a git pull and restart https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-restart-terrariumpi

**Comment by bjornarfonn** [comment]
Working!! Thank you!

**Comment by theyosh** [comment]
Also the HC-SR04 sensor?

**Comment by bjornarfonn** [comment]
No, that remains. When i add it, the software keeps loading but never says changes are saved.. and then the software just freezes. Nothing in the terminal when adding, but after freezing and running the restart command, this shows up;

  result['ok'] = self.__terrariumEngine.set_config(path,postdata,request.files)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 1024, in set_config
    update_ok = self.set_sensors_config(data)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 597, in set_sensors_config
    self.__load_sensors(data)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 168, in __load_sensors
    self.__unit_type)
  File "/home/pi/TerrariumPI/terrariumSensor.py", line 274, in __init__
    self.update()
  File "/home/pi/TerrariumPI/terrariumSensor.py", line 388, in update
    current = sensor.get_distance()
  File "/home/pi/TerrariumPI/terrariumGPIOSensor.py", line 202, in get_distance
    return self.get_current()
  File "/home/pi/TerrariumPI/terrariumGPIOSensor.py", line 193, in get_current
    self.__get_raw_data()
  File "/home/pi/TerrariumPI/terrariumGPIOSensor.py", line 181, in __get_raw_data
    while GPIO.input(terrariumUtils.to_BCM_port_number(self.__datapin))==0:
  File "/home/pi/TerrariumPI/terrariumUtils.py", line 73, in to_BCM_port_number
    if index in pinout:

But i thought that you mentioned is probably not in the code, but perhaps just a bad sensor? so thats why i completed the issue

**Comment by bjornarfonn** [comment]
Tried a new sensor today, rebuilt the voltage divider and used the modmypi guide for wiring (1k and 2k resistors) Still wont add.

Could it be something with the pi zero? Anyone else have this working with a zero?

**Comment by theyosh** [comment]
Hmm, I actually do not know. I do not use them for this project. But I do have a hunch...

If you are able to edit the file `/home/pi/TerrariumPI/terrariumGPIOSensor.py` at line 11 and 12.

Change it from:
```
from gevent import monkey, sleep
monkey.patch_all()
```

to

```
#from gevent import monkey, sleep
#monkey.patch_all()
from time import sleep
```

And restart
It could be that some gevent concurrency code will not work well in a Pi Zero.... but this is a hunch

**Comment by bjornarfonn** [comment]
I managed tol solve this yesterday. Turns out (and please note this might only be an issue on pi zero) you have to use the BOARD pinout number, not the BCM. In my case, GPIO 18 & 24 becomes 12 & 18. I dont know if there is a way to configure this for the users? 

My sensor is now working perfectly and have been running non stop for the last 8 hours.

Perhaps, if this is only rpi zero, you can add a comment about this to end-users in readme or in the software?

Thank you very much for the support so far.

**Comment by theyosh** [comment]
Euh, that is all documented. All GPIO input pins are physical numbers. https://github.com/theyosh/TerrariumPI#gpio-numbering and https://github.com/theyosh/TerrariumPI/wiki/Hardware

So I did not expect that was the case here.... but it is now all sorted out.

**Comment by bjornarfonn** [comment]
I thought it would do both bcm and board. Apologies for the
misunderstanding on my part.

Den fre. 17. aug. 2018, 08:36 skrev TheYOSH <notifications@github.com>:
